In [10]:
import pandas as pd; pd.set_option('display.max_columns', None), pd.set_option('display.max_rows', None)
from pandas import DataFrame

from datetime import date

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import metrics 

import numpy as np

from matplotlib import pyplot as plt

import tensorflow as tf
from tensorflow import keras
#from keras.layers import Input, Flatten, Dense

import pybaseball as pyb
from pybaseball import team_game_logs
from pybaseball import schedule_and_record
from pybaseball import playerid_reverse_lookup

import streamlit as st
import warnings
warnings.filterwarnings('ignore')

In [11]:
#pulls hitting data from baseball reference for a specified team and year
def get_batting (team, year):
    url = 'https://www.baseball-reference.com/teams/{}/{}.shtml#all_team_batting'
    next_url = url.format(team, year)
    data = pd.read_html(next_url, header = 0)
    return data[-2]

#get_batting('TBR', 2021)

#pulls pitching data from baseball reference for a specified team and year
def get_pitching (team, year):
    url = 'https://www.baseball-reference.com/teams/{}/{}.shtml#team_pitching'
    next_url = url.format(team, year)
    data = pd.read_html(next_url)
    return data[-1]

#removes day of the week from date
def clean_date(team):
    k = schedule_and_record(2021, team)
    b = k.Date
    my_list = []
    for i in b:
        if "," in i:
            param, value = i.split(",",1)
            my_list.append(value)
    k['Date'] = my_list
    return k

all_teams = ['TBR', 'BOS', 'NYY', 'TOR', 'BAL', 'CHW', 'CLE', 'DET', 'KC', 'MIN', 'HOU', 'OAK',
           'SEA', 'LAA', 'TEX','NYM','PHI', 'ATL', 'WSN', 'MIA', 'MIL', 'CIN', 'STL', 'CHC', 'PIT',
          'SF', 'LAD', 'SD', 'COL', 'ARI']
#takes in one team as an arg and spits out todays matchup for that team along with probable pitchers 
def get_today(team):
    try:
        u = 'https://www.baseball-reference.com/teams/{}/2021.shtml#team_pitching'
        next_u = u.format(team)
        d = pd.read_html(next_u)
        matchup = d[0].drop(columns = [1, 2])
        matchup.rename(columns = {0:'Date'}, inplace = True)
        param, value = matchup.Date[0].split(",",1)
        matchup.replace(matchup.Date[0], param, inplace = True)
        pitchers = d[1]
        pitchers.rename(columns = {0:'Team', 1:'Pitchers'}, inplace = True)
        home_starter = pitchers.Pitchers[1]
        away_starter = pitchers.Pitchers[0]
        listy = ['date', away_starter, home_starter]
        pitchers.rename(columns = {0:'Team', 1:'Pitchers'}, inplace = True)
        matchup['Pitchers'] = listy
    except: 
        home_starter = 'undefined'
        away_starter = 'undefined'
        pass
    return matchup
#takes in a team as an arg and spits out the home team in its current matchup
def get_home(team):
    try:
        u = 'https://www.baseball-reference.com/teams/{}/2021.shtml#team_pitching'
        next_u = u.format(team)
        d = pd.read_html(next_u)
        matchup = d[1]
        matchup.rename(columns = {0:'Team'}, inplace = True)
        homeTeam = matchup.Team[1]
        awayTeam = matchup.Team[0]
    except: 
        homeTeam = 'undefined'
        awayTeam = 'undefined'
        pass
    return homeTeam
#creates formatted df for passing into the model. takes in two teams that are facing eachother on a given day
#and formats a df to display all of their relevant stats and elo 

#pqm is a self created pitcher quality metric. takes into acccount a collection of pitchers stats and reconciles them
#into one, whole number stat
def pqm(team, pitcher_name):
    team_data = get_pitching(team, 2021)
    pitcher_data = team_data[team_data['Name'].str.contains(pitcher_name)]
    era = float(pitcher_data.ERA.iloc[0])
    whip = float(pitcher_data.WHIP.iloc[0])
    bb9 = float(pitcher_data.BB9.iloc[0])
    fip = float(pitcher_data.FIP.iloc[0])
    pqm = round((((era * fip)/2)* (whip * bb9))/2)
    return pqm
def elo(team):
    team_sr = schedule_and_record(2021, team)
    team_sr.rename(columns = {'W/L' : 'Result', 'W-L' : 'Record'}, inplace = True)
    num_wins = team_sr.Result.str.count('W').sum()
    num_losses = team_sr.Result.str.count('L').sum()
    elo = 1500 + (25 * num_wins) - (25 * num_losses)
    return elo

#pqm('TBR', 'Shane McClanahan')

def create_df(team, team2):
    data = get_today(team)
    p1 = data.Pitchers[1]
    p2 = data.Pitchers[2]
    t1 = data.Date[1]
    t2 = data.Date[2]
    data['t1_pqm'] = pqm(team, p1)
    data['t2_pqm'] = pqm(team2, p2)
    data['t1_elo'] = elo(team)
    data['t2_elo'] = elo(team2)
    data['home_team'] = t2
    data['away_team'] = t1
    data['home_pitcher'] = p2
    data['away_pitcher'] = p1
    data['t1_era'] = get_era(team, p1)
    data['t2_era'] = get_era(team2, p2)
    data['t1_bb9'] = get_bb9(team, p1)
    data['t2_bb9'] = get_bb9(team2, p2)
    data['t1_fip'] = get_fip(team, p1)
    data['t2_fip'] = get_fip(team2, p2)
    data['t1_so'] = get_so(team, p1)
    data['t2_so'] = get_so(team2, p2)
    data['t1_ba'] = get_ba(team)
    data['t2_ba'] = get_ba(team2)
    data['t1_ops'] = get_ops(team)
    data['t2_ops'] = get_ops(team2)
    data.drop(data.index[[1,2]], inplace= True)
    data.drop(columns = 'Pitchers', inplace = True)
    return data 

def get_era(team, pitcher_name):
    team_data = get_pitching(team,2021)
    pitcher_data = team_data[team_data['Name'].str.contains(pitcher_name)]
    era = float(pitcher_data.ERA.iloc[0])
    return era
#get_era('NYY', 'Lucas Luetge')
def get_bb9(team, pitcher_name):
    team_data = get_pitching(team,2021)
    pitcher_data = team_data[team_data['Name'].str.contains(pitcher_name)]
    bb9 = float(pitcher_data.BB9.iloc[0])
    return bb9
def get_fip(team, pitcher_name):
    team_data = get_pitching(team,2021)
    pitcher_data = team_data[team_data['Name'].str.contains(pitcher_name)]
    fip = float(pitcher_data.FIP.iloc[0])
    return fip
def get_whip(team, pitcher_name):
    team_data = get_pitching(team,2021)
    pitcher_data = team_data[team_data['Name'].str.contains(pitcher_name)]
    whip = float(pitcher_data.WHIP.iloc[0])
    return whip
def get_so(team, pitcher_name):
    team_data = get_pitching(team,2021)
    pitcher_data = team_data[team_data['Name'].str.contains(pitcher_name)]
    so = float(pitcher_data.SO.iloc[0])
    return so
def get_ba(team):
    team_data = team_game_logs(2021, team)
    ba = team_data.BA
    current_ba = ba.iloc[-1]
    return current_ba
def get_ops(team):
    team_data = team_game_logs(2021, team)
    ops = team_data.OPS
    current_ops = ops.iloc[-1]
    return current_ops


In [51]:
stats1 = pd.concat([create_df('DET', 'TBR'),
               create_df('COL', 'WSN'),
                 create_df('CLE', 'NYY'), create_df('MIN', 'TOR'),
                 create_df('LAD', 'CIN'),
                   create_df('PHI', 'NYM'), create_df('PIT', 'MIA'),
                   create_df('CHW', 'TEX'), create_df('ARI', 'HOU'),
                   create_df('SEA', 'KCR'), create_df('CHC', 'MIL'),
                   create_df('ATL', 'SFG')])
# 0= team1 win, 1 = team2 win , team2 is home, team1 is away

In [55]:
stats1

Date  t1_pqm  t2_pqm  t1_elo  t2_elo             home_team  \
0  Sep 17      13      28  1325.0  2375.0        Tampa Bay Rays   
0  Sep 17      13      60  1250.0   850.0  Washington Nationals   
0  Sep 17      13      23  1450.0  1925.0      New York Yankees   
0  Sep 17       8       9  1025.0  1950.0     Toronto Blue Jays   
0  Sep 17       4      19  2525.0  1625.0       Cincinnati Reds   
0  Sep 17       4      18  1550.0  1425.0         New York Mets   
0  Sep 17      64      11   550.0   950.0         Miami Marlins   
0  Sep 17      19      21  2000.0   550.0         Texas Rangers   
0  Sep 17      16      22   200.0  2150.0        Houston Astros   
0  Sep 17       9      30  1750.0  1150.0    Kansas City Royals   
0  Sep 17      50      18  1125.0  2300.0     Milwaukee Brewers   
0  Sep 17      18       5  1700.0  2575.0  San Francisco Giants   

               away_team       home_pitcher       away_pitcher  t1_era  \
0         Detroit Tigers        Luis Patino         Casey Mize    3.66   
0       Colorado Rockies        Josiah Gray     German Marquez    3.93   
0      Cleveland Indians       Corey Kluber        Zach Plesac    4.45   
0        Minnesota Twins       Hyun Jin Ryu     Michael Pineda    3.87   
0    Los Angeles Dodgers      Luis Castillo     Walker Buehler    2.32   
0  Philadelphia Phillies     Taijuan Walker       Zack Wheeler    2.86   
0     Pittsburgh Pirates  Elieser Hernandez          Wil Crowe    5.97   
0      Chicago White Sox       Taylor Hearn        Dylan Cease    4.22   
0   Arizona Diamondbacks     Brandon Bielak  Madison Bumgarner    4.66   
0       Seattle Mariners       Brady Singer       Chris Flexen    3.73   
0           Chicago Cubs      Adrian Houser        Zach Davies    5.40   
0         Atlanta Braves         Logan Webb       Ian Anderson    3.61   

   t2_era  t1_bb9  t2_bb9  t1_fip  t2_fip  t1_so  t2_so  t1_ba  t2_ba  t1_ops  \
0    4.62     2.6     3.8    4.85    4.72  108.0   65.0  0.241  0.240   0.709   
0    5.85     3.0     4.1    3.71    6.87  167.0   39.0  0.247  0.258   0.729   
0    4.02     2.1     4.2    4.67    4.12   88.0   72.0  0.236  0.236   0.709   
0    4.11     1.7     1.9    4.18    3.82   79.0  131.0  0.240  0.267   0.735   
0    4.24     2.3     3.5    3.23    3.84  189.0  171.0  0.242  0.248   0.752   
0    4.29     1.9     3.1    2.67    4.46  225.0  137.0  0.242  0.239   0.731   
0    4.14     4.5     1.7    5.91    5.14   95.0   37.0  0.235  0.235   0.669   
0    3.99     3.8     3.4    3.66    5.00  202.0   83.0  0.255  0.231   0.755   
0    4.47     2.5     3.5    4.64    4.32  112.0   37.0  0.235  0.270   0.689   
0    4.85     2.0     3.8    3.86    4.14  107.0  124.0  0.223  0.247   0.681   
0    3.25     4.4     4.1    5.42    4.31  109.0   98.0  0.233  0.235   0.711   
0    2.80     3.9     2.3    3.95    2.90  107.0  132.0  0.242  0.248   0.754   

   t2_ops  Result  
0   0.745       1  
0   0.754       0  
0   0.725       1  
0   0.798       0  
0   0.754       1  
0   0.708       0  
0   0.677       0  
0   0.670       0  
0   0.785       1  
0   0.700       0  
0   0.718       1  
0   0.771       1

In [317]:
def todays_matchups(date):#date in numeric format ie, 20210909
    url = 'https://www.cbssports.com/mlb/schedule/{}'
    u2 = url.format(date)
    data = pd.read_html(u2)
    v = data[1]
    arrl = len(v.Away)
    i = 0
    k = 0
    while i < arrl:
        obj = v.Away[i]
        if obj == 'Detroit':
            v.replace(obj, 'DET', inplace = True)
        if obj == 'Minnesota':
            v.replace(obj, 'MIN', inplace = True)
        if obj == 'N.Y. Mets':
            v.replace(obj, 'NYM', inplace = True)
        if obj == 'Kansas City':
            v.replace(obj, 'KCR', inplace = True)
        if obj == 'Toronto':
            v.replace(obj, 'TOR', inplace = True)
        if obj == 'Tampa Bay':
            v.replace(obj, 'TBR', inplace = True)
        if obj == 'Washington':
            v.replace(obj, 'WSN', inplace = True)
        if obj == 'Cincinnati':
            v.replace(obj, 'CIN', inplace = True)
        if obj == 'Philadelphia':
            v.replace(obj, 'PHI', inplace = True)
        if obj == 'L.A. Dodgers':
            v.replace(obj, 'LAD', inplace = True)
        if obj == 'L.A. Angels':
            v.replace(obj, 'LAA', inplace = True)
        if obj == 'Chi. White Sox':
            v.replace(obj, 'CHW', inplace = True)
        if obj == 'Cleveland':
            v.replace(obj, 'CLE', inplace = True)
        if obj == 'Pittsburgh':
            v.replace(obj, 'PIT', inplace = True)
        if obj == 'Miami':
            v.replace(obj, 'MIA', inplace = True)
        if obj == 'Baltimore':
            v.replace(obj, 'BAL', inplace = True)
        if obj == 'N.Y. Yankees':
            v.replace(obj, 'NYY', inplace = True)
        if obj == 'Boston':
            v.replace(obj, 'BOS', inplace = True)
        if obj == 'Atlanta':
            v.replace(obj, 'ATL', inplace = True)
        if obj == 'Chi. Cubs':
            v.replace(obj, 'CHC', inplace = True)
        if obj == 'Milwaukee':
            v.replace(obj, 'MIL', inplace = True)
        if obj == 'St. Louis':
            v.replace(obj, 'STL', inplace = True)
        if obj == 'San Diego':
            v.replace(obj, 'SDP', inplace = True)
        if obj == 'Oakland':
            v.replace(obj, 'OAK', inplace = True)
        if obj == 'Colorado':
            v.replace(obj, 'COL', inplace = True)
        i+=1
    while k < arrl:
        obj2 = v.Home[k]
        if obj2 == 'Detroit':
            v.replace(obj2, 'DET', inplace = True)
        if obj2 == 'Minnesota':
            v.replace(obj2, 'MIN', inplace = True)
        if obj2 == 'N.Y.Mets':
            v.replace(obj2, 'NYM', inplace = True)
        if obj2 == 'Kansas City':
            v.replace(obj2, 'KCR', inplace = True)
        if obj2 == 'Toronto':
            v.replace(obj2, 'TOR', inplace = True)
        if obj2 == 'Tampa Bay':
            v.replace(obj2, 'TBR', inplace = True)
        if obj2 == 'Washington':
            v.replace(obj2, 'WSN', inplace = True)
        if obj2 == 'Cincinatti':
            v.replace(obj2, 'CIN', inplace = True)
        if obj2 == 'Philadelphia':
            v.replace(obj2, 'PHI', inplace = True)
        if obj2 == 'L.A. Dodgers':
            v.replace(obj2, 'LAD', inplace = True)
        if obj2 == 'L.A. Angels':
            v.replace(obj2, 'LAA', inplace = True)
        if obj2 == 'Chi. White Sox':
            v.replace(obj2, 'CHW', inplace = True)
        if obj2 == 'Cleveland':
            v.replace(obj2, 'CLE', inplace = True)
        if obj2 == 'Pittsburgh':
            v.replace(obj2, 'PIT', inplace = True)
        if obj2 == 'Miami':
            v.replace(obj2, 'MIA', inplace = True)
        if obj2 == 'Baltimore':
            v.replace(obj2, 'BAL', inplace = True)
        if obj2 == 'N.Y. Yankees':
            v.replace(obj2, 'NYY', inplace = True)
        if obj2 == 'Boston':
            v.replace(obj2, 'BOS', inplace = True)
        if obj2 == 'Atlanta':
            v.replace(obj2, 'ATL', inplace = True)
        if obj2 == 'Chi. Cubs':
            v.replace(obj2, 'CHC', inplace = True)
        if obj2 == 'Milwaukee':
            v.replace(obj2, 'MIL', inplace = True)
        if obj2 == 'St. Louis':
            v.replace(obj2, 'STL', inplace = True)
        if obj2 == 'San Diego':
            v.replace(obj2, 'SDP', inplace = True)
        if obj2 == 'Oakland':
            v.replace(obj2, 'OAK', inplace = True)
        if obj2 == 'Colorado':
            v.replace(obj2, 'COL', inplace = True)
        k+=1
    
    return data

In [185]:
today = todays_matchups()

todays_matchups = today

In [319]:
pd.read_csv('0821log.csv')

Date  t1_pqm  t2_pqm  t1_elo  t2_elo            home_team  \
0   Aug 20      22       6  1150.0  1950.0     New York Yankees   
1   Aug 20      12      66  1725.0   400.0    Baltimore Orioles   
2   Aug 20      13       7  1325.0  1675.0    Toronto Blue Jays   
3   Aug 20      16       0   575.0  1875.0       Boston Red Sox   
4   Aug 20      12      28  2000.0  2200.0       Tampa Bay Rays   
5   Aug 20       2      22  1000.0  1725.0      Cincinnati Reds   
6   Aug 20      17      15  1750.0  2025.0       Houston Astros   
7   Aug 20      76       4   575.0  1600.0  St. Louis Cardinals   
8   Aug 20       0      13   500.0  1225.0     Colorado Rockies   
9   Aug 20      13      12  2375.0  1900.0    Oakland Athletics   
10  Aug 20      87       4  1475.0  2250.0  Los Angeles Dodgers   

               away_team         home_pitcher       away_pitcher  t1_era  \
0        Minnesota Twins    Nestor Cortes Jr.     Charlie Barnes    4.91   
1         Atlanta Braves          Keegan Akin          Max Fried    3.78   
2         Detroit Tigers           Robbie Ray    Tyler Alexander    4.57   
3          Texas Rangers           Chris Sale       Dane Dunning    4.06   
4      Chicago White Sox        Michael Wacha      Lucas Giolito    3.83   
5          Miami Marlins           Sonny Gray  Elieser Hernandez    2.84   
6       Seattle Mariners  Lance McCullers Jr.      Yusei Kikuchi    3.82   
7     Pittsburgh Pirates        Miles Mikolas       Mitch Keller    6.86   
8   Arizona Diamondbacks        Austin Gomber      Tyler Gilbert    0.00   
9   San Francisco Giants     James Kaprielian          Alex Wood    4.14   
10         New York Mets       Walker Buehler    Carlos Carrasco   10.32   

    t2_era  t1_bb9  t2_bb9  t1_fip  t2_fip  t1_so  t2_so  t1_ba  t2_ba  \
0     2.55     2.5     2.6    5.14    3.26    9.0   53.0  0.244  0.237   
1     8.13     2.8     3.7    3.51    4.78  113.0   54.0  0.243  0.238   
2     2.88     1.9     2.4    4.48    3.85   53.0  167.0  0.241  0.265   
3     3.60     3.2     0.0    3.55    5.18   97.0    8.0  0.223  0.259   
4     5.91     2.7     2.5    4.04    5.09  161.0   76.0  0.251  0.238   
5     4.47     0.7     3.7    4.68    3.79   13.0  113.0  0.237  0.253   
6     3.22     3.3     4.3    4.48    3.47  140.0  136.0  0.222  0.266   
7     2.25     5.0     2.3    4.77    3.18   60.0    3.0  0.233  0.237   
8     4.09     3.6     2.8    2.78    3.98   10.0  100.0  0.236  0.250   
9     3.33     2.7     3.1    3.77    4.01  121.0   83.0  0.247  0.236   
10    2.09     2.4     2.4    7.59    3.13   12.0  162.0  0.235  0.247   

    t1_ops  t2_ops  Result  
0    0.745   0.723       1  
1    0.756   0.699       0  
2    0.708   0.787       0  
3    0.657   0.766       1  
4    0.752   0.740       0  
5    0.682   0.767       1  
6    0.681   0.775       1  
7    0.662   0.702       0  
8    0.691   0.728       1  
9    0.763   0.725       1  
10   0.691   0.764       1

In [304]:
def predict(team, team2):
    dataset = create_df(team, team2)
    t1_pqm = dataset.t1_pqm
    t2_pqm = dataset.t2_pqm
    t1_elo = dataset.t1_elo
    t2_elo = dataset.t2_elo
    t1_era = dataset.t1_era
    t2_era = dataset.t2_era
    t1_bb9 = dataset.t1_bb9
    t2_bb9 = dataset.t2_bb9
    t1_fip = dataset.t1_fip
    t2_fip = dataset.t2_fip
    t1_ba = dataset.t1_ba
    t2_ba = dataset.t2_ba
    t1_ops = dataset.t1_ops
    t2_ops = dataset.t2_ops
    t1_so = dataset.t1_so
    t2_so = dataset.t2_so
    dataf = pd.DataFrame({'t1_pqm':t1_pqm,' t2_pqm':t2_pqm,'t1_elo':t1_elo, 't2_elo':t2_elo,
                      't1_era':t1_era, 't2_era':t2_era, 't1_bb9':t1_bb9,'t2_bb9': t2_bb9,
                     't1_fip':t1_fip, 't2_fip':t2_fip,'t1_so':t1_so,'t2_so':t2_so, 't1_ba':t1_ba,'t2_ba':t2_ba,'t1_ops':t1_ops,
                      't2_ops':t2_ops})
    return dataf

d = predict('CHW', 'OAK')
actual = dummies(d)
model.predict(actual)



array([[1., 0.]], dtype=float32)

In [308]:
todays_matchups(20210909)

KeyError: "['Time / TV' 'Venue' 'Home Starter' 'Away Starter' 'Buy Tickets'] not found in axis"

In [296]:
def dummies(data):
    val = pd.get_dummies(data)
    return val
dummies(bigstats)

t1_pqm  t2_pqm  t1_elo  t2_elo  t1_era  t2_era  t1_bb9  t2_bb9  t1_fip  \
0       17      11  1925.0  2375.0    5.12    3.59     2.7     2.8    3.48   
1       71      27   575.0  1100.0    6.75    3.09     4.8     5.0    4.86   
2       30      18  1550.0  1150.0    4.83    5.30     4.6     2.5    4.70   
3       17      27  1700.0  1225.0    3.60    6.08     3.4     2.3    4.86   
4        9      25  1825.0  1300.0    3.66    5.46     2.5     2.7    3.26   
5       17       6  2250.0  2375.0    3.61    2.65     3.4     2.5    4.26   
0       15       8  1075.0  1525.0    6.00    3.32     2.6     2.1    3.50   
1       16      35  1500.0   925.0    6.59    5.23     1.6     2.6    4.91   
2      186      84  1175.0   250.0    9.82    7.71     6.5     4.3    5.35   
3       13       3  1800.0  1975.0    3.80    2.73     2.6     1.9    3.78   
4        6      15  2400.0  1950.0    3.00    4.88     2.5     2.6    2.73   
5        9       9   925.0  1700.0    4.08    3.51     1.7     2.4    4.40   
6       10       3  1675.0  1225.0    2.97    1.59     2.8     1.6    3.78   
7        9      14  1625.0  2225.0    4.54    3.43     2.1     3.2    3.53   
8       11      20  1800.0  2075.0    5.14    4.32     2.0     3.1    3.66   
9        5      32  2450.0  1200.0    2.56    6.13     2.4     2.6    2.90   
10      88      26   525.0   300.0    9.82    4.34     3.7     4.0    5.48   
11      35      30  1450.0  1725.0    4.00    4.31     5.0     5.0    3.94   
0       37      69  1450.0   325.0    5.87    7.92     3.2     3.8    5.35   
1       18      14  1750.0  2225.0    4.15    4.15     3.6     2.5    3.70   
2        4       7  1950.0  1675.0    2.38    3.54     2.5     1.9    2.57   
3        2      61  1575.0   625.0    1.00    6.35     3.0     4.7    3.06   
4       26       7   450.0  1500.0    4.59    4.17     3.9     1.4    4.38   
5       13      46  2450.0  1400.0    4.11    8.82     2.8     2.2    3.63   
6       32      85   550.0  1500.0    5.33    7.52     3.0     4.8    5.54   
7        9       2  1100.0  1900.0    6.00    1.80     2.3     0.9    2.17   
8       31       9  1075.0   925.0    5.82    4.15     2.8     1.6    5.39   
9        2       7  2325.0  1700.0    2.11    3.70     1.7     2.1    2.18   
10      13      13  2050.0  1825.0    3.94    3.25     2.6     3.3    4.21   
11      43      22  1150.0  1775.0    5.43    4.22     4.2     3.4    4.62   
0        9       3  2250.0  1525.0    4.57    2.77     1.5     1.9    4.32   
1       11       6  1975.0  1650.0    3.77    2.79     2.6     2.2    3.98   
2       10      16  2425.0  1425.0    3.89    3.86     2.1     3.3    3.93   
3       15      23  1075.0  1925.0    4.38    4.43     2.3     3.9    4.79   
4       19      68  1375.0  1550.0    4.02    7.08     3.0     4.0    4.86   
5       13      45  1225.0  1075.0    3.80    5.04     3.2     4.5    3.57   
6       18      15  1175.0  2050.0    5.34    3.21     2.5     4.2    4.27   
7       22       4  1775.0  2200.0    4.35    2.48     3.7     2.3    3.97   
8        4      44  2300.0  1725.0    2.11    4.82     2.3     5.5    3.13   

    t2_fip  t1_so  t2_so  t1_ba  t2_ba  t1_ops  t2_ops  Result  Date_Aug 25  \
0     3.37  150.0  117.0  0.259  0.239   0.769   0.741       0            0   
1     4.91   68.0   45.0  0.233  0.230   0.664   0.702       1            0   
2     4.37  107.0  142.0  0.237  0.244   0.716   0.691       0            0   
3     5.30   40.0   54.0  0.242  0.248   0.750   0.729       0            0   
4     4.55  167.0   34.0  0.236  0.241   0.722   0.704       0            0   
5     3.03   82.0  111.0  0.235  0.244   0.719   0.756       1            0   
0     4.27   25.0   76.0  0.242  0.239   0.739   0.719       0            0   
1     7.62   28.0    4.0  0.240  0.235   0.705   0.677       0            0   
2     5.25    8.0   15.0  0.244  0.240   0.691   0.707       1            0   
3     2.54  116.0  215.0  0.264  0.236   0.785   0.722       0            0   
4     3.41   3

In [237]:
while i < 100: 
    prediction = predict('SEA', 'HOU')
    print(prediction)
    

tf.Tensor([[-0.20717502]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.10259485]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.4181844]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.42294866]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.73463136]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.91016924]], shape=(1, 1), dtype=float32)
tf.Tensor([[0.94528973]], shape=(1, 1), dtype=float32)
tf.Tensor([[0.01856589]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.2309793]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.0579536]], shape=(1, 1), dtype=float32)
tf.Tensor([[0.85025036]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.28845203]], shape=(1, 1), dtype=float32)
tf.Tensor([[-1.351032]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.312781]], shape=(1, 1), dtype=float32)
tf.Tensor([[-1.2704483]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.7918243]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.3402809]], shape=(1, 1), dtype=float32)


KeyboardInterrupt: 

In [254]:
url = 'https://www.cbssports.com/mlb/schedule/20210909'
data = pd.read_html(url)
data[0]

Away          Home Time / TV                            Venue  \
0    L.A. Dodgers     St. Louis   1:15 pm                    Busch Stadium   
1  Chi. White Sox       Oakland   3:37 pm  Oakland-Alameda County Coliseum   
2       Minnesota     Cleveland   6:10 pm                Progressive Field   
3       N.Y. Mets         Miami   6:40 pm                   loanDepot park   
4     Kansas City     Baltimore   7:05 pm      Oriole Park at Camden Yards   
5        Colorado  Philadelphia   7:05 pm               Citizens Bank Park   
6         Toronto  N.Y. Yankees   7:05 pm                   Yankee Stadium   
7      Washington       Atlanta   7:20 pm                      Truist Park   

                                        Home Starter  \
0  J. Woodford  (2-3, 4.47 ERA)  J. Woodford  (2-...   
1  S. Manaea  (8-9, 3.91 ERA)  S. Manaea  (8-9, 3...   
2  C. Quantrill  (4-3, 3.15 ERA)  C. Quantrill  (...   
3  J. Luzardo  (3-3, 7.62 ERA)  J. Luzardo  (3-3,...   
4  J. Means  (5-6, 3.47 ERA)  J. Means  (5-6, 3.4...   
5  R. Suarez  (6-4, 1.38 ERA)  R. Suarez  (6-4, 1...   
6  N. Cortes  (2-2, 2.67 ERA)  N. Cortes  (2-2, 2...   
7  H. Ynoa  (4-5, 3.19 ERA)  H. Ynoa  (4-5, 3.19 ...   

                                        Away Starter  \
0  T. Gonsolin  (2-1, 2.78 ERA)  T. Gonsolin  (2-...   
1  R. Lopez  (3-1, 2.08 ERA)  R. Lopez  (3-1, 2.0...   
2  R. Dobnak  (1-7, 7.64 ERA)  R. Dobnak  (1-7, 7...   
3  M. Stroman  (9-12, 2.93 ERA)  M. Stroman  (9-1...   
4  C. Hernandez  (5-1, 3.57 ERA)  C. Hernandez  (...   
5  A. Senzatela  (4-9, 4.16 ERA)  A. Senzatela  (...   
6  J. Berrios  (2-2, 3.73 ERA)  J. Berrios  (2-2,...   
7  E. Fedde  (6-9, 5.27 ERA)  E. Fedde  (6-9, 5.2...   

                  Buy Tickets  
0   Tickets Starting at $6.00  
1   Tickets Starting at $7.48  
2   Tickets Starting at $8.00  
3   Tickets Starting at $6.00  
4  Tickets Starting at $10.00  
5         Tickets Starting at  
6         Tickets Starting at  
7   Tickets Starting at $6.00

In [287]:


y = t.Result
X = t.drop(columns = 'Result')

X = X.values.astype('float32')
y = y.values.astype('float32')

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)
X_train, X_validation, y_train, y_validation = train_test_split(X, y, test_size = 0.2)

model=keras.Sequential([keras.layers.Dense(20,activation=tf.nn.relu),
                        keras.layers.Dense(2,activation='softmax')])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['acc'])
history = model.fit(X_train,y_train,epochs=20, validation_data=(X_validation, y_validation))

#all variables within features list are single values, ex: .351, 11, .991, etc.

Epoch 1/20
1/1 [==============================] - 0s 361ms/step - loss: 362.8563 - acc: 0.3548 - val_loss: 204.2546 - val_acc: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 18ms/step - loss: 342.4841 - acc: 0.3548 - val_loss: 186.8354 - val_acc: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 20ms/step - loss: 322.0881 - acc: 0.3548 - val_loss: 169.3922 - val_acc: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 18ms/step - loss: 301.6678 - acc: 0.3548 - val_loss: 151.9245 - val_acc: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 17ms/step - loss: 281.2231 - acc: 0.3548 - val_loss: 134.4319 - val_acc: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 17ms/step - loss: 260.7785 - acc: 0.3871 - val_loss: 116.9196 - val_acc: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 18ms/step - loss: 240.5316 - acc: 0.3871 - val_loss: 99.3904 - val_acc: 0.5000
Epoch 8/20
1/1 [==============================] - 0s 20ms/step - loss

In [288]:
#stats1['Result'] = [0, 1, 0, 0, 0, 1 ]
t = bigstats.drop(columns = ['Date', 'home_team', 'away_team', 'home_pitcher', 'away_pitcher'])
newdf = pd.get_dummies(t)
tester = pd.DataFrame({'t1_pqm':'17', 't2_pqm':'11','t1_elo':'1925', 't2_elo':'2375',
                      't1_era':'5.12', 't2_era':'3.59', 't1_bb9':'2.7','t2_bb9': '2.8',
                     't1_fip':'3.48', 't2_fip':'3.37','t1_so':'150.0','t2_so':'117.0', 't1_ba':'0.259','t2_ba':'0.239','t1_ops':'0.769',
                      't2_ops':'0.741'}, index = [0])
testerr = pd.get_dummies(tester)
model.predict(testerr)

array([[0.8334366 , 0.16656333]], dtype=float32)

In [27]:
newstats = stats1[stats1.home_team != 'New York Mets']

In [38]:
stats1

Date  t1_pqm  t2_pqm  t1_elo  t2_elo             home_team  \
0  Sep 16      13       6  1350.0  2350.0        Tampa Bay Rays   
0  Sep 16      14       0  1600.0   575.0    Pittsburgh Pirates   
0  Sep 16      20      40  1775.0  1175.0    Kansas City Royals   
0  Sep 16      10       3  1425.0  2025.0     Chicago White Sox   
0  Sep 16      13       5  1625.0  2600.0  San Francisco Giants   
0  Sep 16      13      16  1950.0   175.0     Baltimore Orioles   
0  Sep 16      16       5  2125.0   575.0         Texas Rangers   

            away_team    home_pitcher       away_pitcher  t1_era  t2_era  \
0      Detroit Tigers      Louis Head    Tyler Alexander    4.09    2.67   
0     Cincinnati Reds  Connor Overton        Tyler Mahle    3.73    0.00   
0   Oakland Athletics    Daniel Lynch     Paul Blackburn    5.24    5.37   
0  Los Angeles Angels  Reynaldo Lopez          Alex Cobb    3.82    2.05   
0    San Diego Padres   Kevin Gausman     Pierce Johnson    2.98    2.65   
0    New York Yankees     Chris Ellis  Jordan Montgomery    3.71    2.55   
0      Houston Astros      Glenn Otto     Framber Valdez    3.26    6.92   

   t1_bb9  t2_bb9  t1_fip  t2_fip  t1_so  t2_so  t1_ba  t2_ba  t1_ops  t2_ops  \
0     2.3     2.7    4.50    3.43   71.0   27.0  0.242  0.240   0.709   0.744   
0     3.2     0.0    3.93    1.17  188.0    1.0  0.249  0.235   0.755   0.671   
0     2.0     3.9    4.96    4.71   15.0   47.0  0.239  0.247   0.727   0.700   
0     3.0     2.3    2.63    3.28   84.0   40.0  0.246  0.255   0.722   0.756   
0     4.2     2.5    3.48    2.87   67.0  201.0  0.240  0.248   0.719   0.771   
0     3.0     4.1    3.64    5.09  137.0   11.0  0.237  0.240   0.725   0.711   
0     3.9     1.4    3.96    1.63  109.0   16.0  0.269  0.231   0.782   0.671   

   Result  
0       1  
0       0  
0       0  
0       0  
0       0  
0       1  
0       0

In [56]:
 
stats1.to_csv('~/Desktop/mlb/0918log.csv', index = False)